enum NotificationType {
    FRIEND_REQUEST = 'FRIEND_REQUEST',
    NOTIFICATION = 'NOTIFICATION',
    PARENTING_REQUEST = 'PARENTING_REQUEST',
    ORGANIZATION_REQUEST= 'ORGANIZATION_REQUEST',
}

export default NotificationType;