enum UserType {
    PARENT,
    PLAYER,
    COACH,
    BUSINESS,
    LEAGUE,
    ORGANIZATION,
    TRAINER_CAMP_TRAINING,
    TOURNAMENTS,
    REFEREES_OFFICIALS_UMPIRES,
    DEFAULT,
}

export default UserType;